textheader:= (
    "\\ LP Format CPLEX file generated by Mathematica on "<>datestring
    <> "\n \n"
    <> "\n\\ Problem: Bound the score of configuration number "
    <> S[GBLconfig]
    <> "\n\\   arising in Part III of the Kepler Conjecture."
    <> "\n\\ equation 4.1 "
    <> "\n \n \n"
    <> "MAXIMIZE \n xx \n\n"
    <> "\n\nST \n"
    <> sigsum[Lg[GBLregions]] <> " > 0.44298 \n"
    );



WRITEOUTt[i_]:= Module[{stream},
        Initialize[i];
        stream=OpenWrite["/tmp/Z/cplex.lp"<>S[i]];
        WriteString[stream,textheader];
        WriteString[stream,twopi];
        WriteString[stream,group1];
        WriteString[stream,group3];
        WriteString[stream,group5];
        WriteString[stream,hyp41];
        WriteString[stream,hyp42];
        WriteString[stream,solid];
        WriteString[stream,edges];
        WriteString[stream,qedges];
        WriteString[stream,BuildAll055];
        WriteString[stream,brokensolid];
        WriteString[stream,AddExceptScores];
        WriteString[stream,AddMoreExcept];
        WriteString[stream,AddExcess]; (* 1.41 & 1.5 pt at crowded vertices *)
        WriteString[stream,bounds];
		WriteString[stream," xx free "];
        WriteString[stream,"\n\nEND\n\n"];
        WriteString[stream,faceCode];
        Close[stream];
        ];

subb[j_] := (Initialize[j]; Table[StringReplace[vv, subX[j, i]], 
     {i, 1, GBLnumver}])
subX[i_] := {"lp1" -> StringJoin["lp", S[i]], "dih" -> StringVar["y", i]}
 
subX[i_, j_, k_] := {"lp1" -> StringJoin["lp", S[i]], "dih" -> Sdih[i, j, k]}
 
subX[i_, j_] := {"lp1" -> StringJoin["lp", S[i]], "dih" -> StringVar["y", j]}
vv = "read cplex.lp1 lp\nadd\nxx-dih =0\nend\noptimize\n\n"
