
arrangeMain.class :  arrange.java arrangePlus.java arrangeMain.java
	javac -g arrangeMain.java

arrangePlus.class : arrange.java arrangePlus.java
	javac arrangePlus.java

arrange.class : arrange.java
	javac arrange.java
